#!/usr/bin/python

"""Amulet tests on a basic cinder-ceph deployment on precise-icehouse."""

from basic_deployment import CinderCephBasicDeployment

if __name__ == '__main__':
    deployment = CinderCephBasicDeployment(series='precise',
                                           openstack='cloud:precise-icehouse',
                                           source='cloud:precise-updates/icehouse')
    deployment.run_tests()
