#!/usr/bin/python

"""Amulet tests on a basic cinder-ceph deployment on trusty-icehouse."""

from basic_deployment import CinderCephBasicDeployment

if __name__ == '__main__':
    deployment = CinderCephBasicDeployment(series='trusty')
    deployment.run_tests()
