#!/usr/bin/python

"""Amulet tests on a basic cinder-ceph deployment on trusty-kilo."""

from basic_deployment import CinderCephBasicDeployment

if __name__ == '__main__':
    deployment = CinderCephBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-kilo',
                                           source='cloud:trusty-updates/kilo')
    deployment.run_tests()
