#!/usr/bin/python

"""Amulet tests on a basic cinder-ceph deployment on trusty-liberty."""

from basic_deployment import CinderCephBasicDeployment

if __name__ == '__main__':
    deployment = CinderCephBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-liberty',
                                           source='cloud:trusty-updates/liberty')
    deployment.run_tests()
