#!/usr/bin/python

"""Amulet tests on a basic cinder-ceph deployment on vivid-kilo."""

from basic_deployment import CinderCephBasicDeployment

if __name__ == '__main__':
    deployment = CinderCephBasicDeployment(series='vivid')
    deployment.run_tests()
