#!/usr/bin/python

"""Amulet tests on a basic cinder-ceph deployment on wily-liberty."""

from basic_deployment import CinderCephBasicDeployment

if __name__ == '__main__':
    deployment = CinderCephBasicDeployment(series='wily')
    deployment.run_tests()
