#!/usr/bin/python

"""Amulet tests on a basic cinder-ceph deployment on xenial-mitaka."""

from basic_deployment import CinderCephBasicDeployment

if __name__ == '__main__':
    deployment = CinderCephBasicDeployment(series='xenial')
    deployment.run_tests()
